#!/bin/bash


  for file in $(find -type f -name strings_not_translated.xml); do


     sed -i '/name="abc_action_bar_home_description"/d' $file
     sed -i '/name="abc_action_bar_up_description"/d' $file
     sed -i '/name="abc_action_menu_overflow_description"/d' $file
     sed -i '/name="abc_action_mode_done"/d' $file
     sed -i '/name="abc_activity_chooser_view_see_all"/d' $file
     sed -i '/name="abc_activitychooserview_choose_application"/d' $file
     sed -i '/name="abc_capital_off"/d' $file
     sed -i '/name="abc_capital_on"/d' $file
     sed -i '/name="abc_menu_alt_shortcut_label"/d' $file
     sed -i '/name="abc_menu_ctrl_shortcut_label"/d' $file
     sed -i '/name="abc_menu_delete_shortcut_label"/d' $file
     sed -i '/name="abc_menu_enter_shortcut_label"/d' $file
     sed -i '/name="abc_menu_function_shortcut_label"/d' $file
     sed -i '/name="abc_menu_meta_shortcut_label"/d' $file
     sed -i '/name="abc_menu_shift_shortcut_label"/d' $file
     sed -i '/name="abc_menu_space_shortcut_label"/d' $file
     sed -i '/name="abc_menu_sym_shortcut_label"/d' $file
     sed -i '/name="abc_prepend_shortcut_label"/d' $file
     sed -i '/name="abc_search_hint"/d' $file
     sed -i '/name="abc_searchview_description_clear"/d' $file
     sed -i '/name="abc_searchview_description_query"/d' $file
     sed -i '/name="abc_searchview_description_search"/d' $file
     sed -i '/name="abc_searchview_description_submit"/d' $file
     sed -i '/name="abc_searchview_description_voice"/d' $file
     sed -i '/name="abc_shareactionprovider_share_with"/d' $file
     sed -i '/name="abc_shareactionprovider_share_with_application"/d' $file
     sed -i '/name="abc_toolbar_collapse_description"/d' $file
     sed -i '/name="actionbar_button_up_description"/d' $file
     sed -i '/name="afternoon"/d' $file
     sed -i '/name="am"/d' $file
     sed -i '/name="chinese_day_1"/d' $file
     sed -i '/name="chinese_day_10"/d' $file
     sed -i '/name="chinese_day_11"/d' $file
     sed -i '/name="chinese_day_12"/d' $file
     sed -i '/name="chinese_day_13"/d' $file
     sed -i '/name="chinese_day_14"/d' $file
     sed -i '/name="chinese_day_15"/d' $file
     sed -i '/name="chinese_day_16"/d' $file
     sed -i '/name="chinese_day_17"/d' $file
     sed -i '/name="chinese_day_18"/d' $file
     sed -i '/name="chinese_day_19"/d' $file
     sed -i '/name="chinese_day_2"/d' $file
     sed -i '/name="chinese_day_20"/d' $file
     sed -i '/name="chinese_day_21"/d' $file
     sed -i '/name="chinese_day_22"/d' $file
     sed -i '/name="chinese_day_23"/d' $file
     sed -i '/name="chinese_day_24"/d' $file
     sed -i '/name="chinese_day_25"/d' $file
     sed -i '/name="chinese_day_26"/d' $file
     sed -i '/name="chinese_day_27"/d' $file
     sed -i '/name="chinese_day_28"/d' $file
     sed -i '/name="chinese_day_29"/d' $file
     sed -i '/name="chinese_day_3"/d' $file
     sed -i '/name="chinese_day_30"/d' $file
     sed -i '/name="chinese_day_4"/d' $file
     sed -i '/name="chinese_day_5"/d' $file
     sed -i '/name="chinese_day_6"/d' $file
     sed -i '/name="chinese_day_7"/d' $file
     sed -i '/name="chinese_day_8"/d' $file
     sed -i '/name="chinese_day_9"/d' $file
     sed -i '/name="chinese_day_elementary"/d' $file
     sed -i '/name="chinese_digit_eight"/d' $file
     sed -i '/name="chinese_digit_five"/d' $file
     sed -i '/name="chinese_digit_four"/d' $file
     sed -i '/name="chinese_digit_nine"/d' $file
     sed -i '/name="chinese_digit_one"/d' $file
     sed -i '/name="chinese_digit_seven"/d' $file
     sed -i '/name="chinese_digit_six"/d' $file
     sed -i '/name="chinese_digit_ten"/d' $file
     sed -i '/name="chinese_digit_three"/d' $file
     sed -i '/name="chinese_digit_two"/d' $file
     sed -i '/name="chinese_digit_zero"/d' $file
     sed -i '/name="chinese_leap"/d' $file
     sed -i '/name="chinese_month"/d' $file
     sed -i '/name="chinese_month_april"/d' $file
     sed -i '/name="chinese_month_august"/d' $file
     sed -i '/name="chinese_month_december"/d' $file
     sed -i '/name="chinese_month_february"/d' $file
     sed -i '/name="chinese_month_january"/d' $file
     sed -i '/name="chinese_month_july"/d' $file
     sed -i '/name="chinese_month_june"/d' $file
     sed -i '/name="chinese_month_march"/d' $file
     sed -i '/name="chinese_month_may"/d' $file
     sed -i '/name="chinese_month_november"/d' $file
     sed -i '/name="chinese_month_october"/d' $file
     sed -i '/name="chinese_month_september"/d' $file
     sed -i '/name="chinese_symbol_animals_chicken"/d' $file
     sed -i '/name="chinese_symbol_animals_cow"/d' $file
     sed -i '/name="chinese_symbol_animals_dog"/d' $file
     sed -i '/name="chinese_symbol_animals_dragon"/d' $file
     sed -i '/name="chinese_symbol_animals_horse"/d' $file
     sed -i '/name="chinese_symbol_animals_monkey"/d' $file
     sed -i '/name="chinese_symbol_animals_mouse"/d' $file
     sed -i '/name="chinese_symbol_animals_pig"/d' $file
     sed -i '/name="chinese_symbol_animals_rabbit"/d' $file
     sed -i '/name="chinese_symbol_animals_sheep"/d' $file
     sed -i '/name="chinese_symbol_animals_snake"/d' $file
     sed -i '/name="chinese_symbol_animals_tiger"/d' $file
     sed -i '/name="clearable_edittext_clear_description"/d' $file
     sed -i '/name="close"/d' $file
     sed -i '/name="date_picker_label_day"/d' $file
     sed -i '/name="date_picker_label_month"/d' $file
     sed -i '/name="date_picker_label_year"/d' $file
     sed -i '/name="date_picker_lunar"/d' $file
     sed -i '/name="date_time_picker_dialog_title"/d' $file
     sed -i '/name="early_morning"/d' $file
     sed -i '/name="earthly_branches_chen"/d' $file
     sed -i '/name="earthly_branches_chou"/d' $file
     sed -i '/name="earthly_branches_hai"/d' $file
     sed -i '/name="earthly_branches_mao"/d' $file
     sed -i '/name="earthly_branches_shen"/d' $file
     sed -i '/name="earthly_branches_si"/d' $file
     sed -i '/name="earthly_branches_wei"/d' $file
     sed -i '/name="earthly_branches_wu"/d' $file
     sed -i '/name="earthly_branches_xu"/d' $file
     sed -i '/name="earthly_branches_yin"/d' $file
     sed -i '/name="earthly_branches_you"/d' $file
     sed -i '/name="earthly_branches_zi"/d' $file
     sed -i '/name="empty"/d' $file
     sed -i '/name="eras_ad"/d' $file
     sed -i '/name="eras_bc"/d' $file
     sed -i '/name="evening"/d' $file
     sed -i '/name="fmt_chinese_date"/d' $file
     sed -i '/name="fmt_date"/d' $file
     sed -i '/name="fmt_date_day"/d' $file
     sed -i '/name="fmt_date_long_month"/d' $file
     sed -i '/name="fmt_date_long_month_day"/d' $file
     sed -i '/name="fmt_date_long_year_month"/d' $file
     sed -i '/name="fmt_date_long_year_month_day"/d' $file
     sed -i '/name="fmt_date_numeric_day"/d' $file
     sed -i '/name="fmt_date_numeric_month"/d' $file
     sed -i '/name="fmt_date_numeric_month_day"/d' $file
     sed -i '/name="fmt_date_numeric_year"/d' $file
     sed -i '/name="fmt_date_numeric_year_month"/d' $file
     sed -i '/name="fmt_date_numeric_year_month_day"/d' $file
     sed -i '/name="fmt_date_short_month"/d' $file
     sed -i '/name="fmt_date_short_month_day"/d' $file
     sed -i '/name="fmt_date_short_year_month"/d' $file
     sed -i '/name="fmt_date_short_year_month_day"/d' $file
     sed -i '/name="fmt_date_time"/d' $file
     sed -i '/name="fmt_date_time_timezone"/d' $file
     sed -i '/name="fmt_date_timezone"/d' $file
     sed -i '/name="fmt_date_year"/d' $file
     sed -i '/name="fmt_time"/d' $file
     sed -i '/name="fmt_time_12hour"/d' $file
     sed -i '/name="fmt_time_12hour_minute"/d' $file
     sed -i '/name="fmt_time_12hour_minute_pm"/d' $file
     sed -i '/name="fmt_time_12hour_minute_second"/d' $file
     sed -i '/name="fmt_time_12hour_minute_second_millis"/d' $file
     sed -i '/name="fmt_time_12hour_minute_second_millis_pm"/d' $file
     sed -i '/name="fmt_time_12hour_minute_second_pm"/d' $file
     sed -i '/name="fmt_time_12hour_pm"/d' $file
     sed -i '/name="fmt_time_24hour"/d' $file
     sed -i '/name="fmt_time_24hour_minute"/d' $file
     sed -i '/name="fmt_time_24hour_minute_second"/d' $file
     sed -i '/name="fmt_time_24hour_minute_second_millis"/d' $file
     sed -i '/name="fmt_time_millis"/d' $file
     sed -i '/name="fmt_time_minute"/d' $file
     sed -i '/name="fmt_time_minute_second"/d' $file
     sed -i '/name="fmt_time_minute_second_millis"/d' $file
     sed -i '/name="fmt_time_second"/d' $file
     sed -i '/name="fmt_time_second_millis"/d' $file
     sed -i '/name="fmt_time_timezone"/d' $file
     sed -i '/name="fmt_timezone"/d' $file
     sed -i '/name="fmt_weekday"/d' $file
     sed -i '/name="fmt_weekday_date"/d' $file
     sed -i '/name="fmt_weekday_date_time"/d' $file
     sed -i '/name="fmt_weekday_date_time_timezone"/d' $file
     sed -i '/name="fmt_weekday_date_timezone"/d' $file
     sed -i '/name="fmt_weekday_long"/d' $file
     sed -i '/name="fmt_weekday_short"/d' $file
     sed -i '/name="fmt_weekday_time"/d' $file
     sed -i '/name="fmt_weekday_time_timezone"/d' $file
     sed -i '/name="fmt_weekday_timezone"/d' $file
     sed -i '/name="friday"/d' $file
     sed -i '/name="friday_short"/d' $file
     sed -i '/name="friday_shortest"/d' $file
     sed -i '/name="heavenly_stems_bing"/d' $file
     sed -i '/name="heavenly_stems_ding"/d' $file
     sed -i '/name="heavenly_stems_geng"/d' $file
     sed -i '/name="heavenly_stems_gui"/d' $file
     sed -i '/name="heavenly_stems_ji"/d' $file
     sed -i '/name="heavenly_stems_jia"/d' $file
     sed -i '/name="heavenly_stems_ren"/d' $file
     sed -i '/name="heavenly_stems_wu"/d' $file
     sed -i '/name="heavenly_stems_xin"/d' $file
     sed -i '/name="heavenly_stems_yi"/d' $file
     sed -i '/name="midnight"/d' $file
     sed -i '/name="miuix_appcompat_action_mode_deselect_all"/d' $file
     sed -i '/name="miuix_appcompat_action_mode_select_all"/d' $file
     sed -i '/name="miuix_appcompat_action_mode_title_empty"/d' $file
     sed -i '/name="miuix_appcompat_actionbar_immersion_button_more_description"/d' $file
     sed -i '/name="miuix_appcompat_cancel_description"/d' $file
     sed -i '/name="miuix_appcompat_confirm_description"/d' $file
     sed -i '/name="miuix_appcompat_delete_description"/d' $file
     sed -i '/name="miuix_appcompat_deselect_all"/d' $file
     sed -i '/name="miuix_appcompat_deselect_all_description"/d' $file
     sed -i '/name="miuix_appcompat_search_action_mode_cancel"/d' $file
     sed -i '/name="miuix_appcompat_search_input_description"/d' $file
     sed -i '/name="miuix_appcompat_select_all"/d' $file
     sed -i '/name="miuix_appcompat_select_all_description"/d' $file
     sed -i '/name="miuix_appcompat_select_item"/d' $file
     sed -i '/name="miuix_sbl_tracking_progress_labe_pull_to_refresh"/d' $file
     sed -i '/name="miuix_sbl_tracking_progress_labe_refreshed"/d' $file
     sed -i '/name="miuix_sbl_tracking_progress_labe_refreshing"/d' $file
     sed -i '/name="miuix_sbl_tracking_progress_labe_release_to_refresh"/d' $file
     sed -i '/name="miuix_sbl_tracking_progress_labe_up_nodata"/d' $file
     sed -i '/name="miuix_sbl_tracking_progress_labe_up_none"/d' $file
     sed -i '/name="miuix_sbl_tracking_progress_labe_up_refresh"/d' $file
     sed -i '/name="miuix_sbl_tracking_progress_labe_up_refresh_fail"/d' $file
     sed -i '/name="miuix_access_state_desc"/d' $file   
     sed -i '/name="miuix_alphabet_indexer_name"/d' $file   
     sed -i '/name="miuix_indexer_collect"/d' $file   
     sed -i '/name="miuix_indexer_selected"/d' $file       
     sed -i '/name="monday"/d' $file
     sed -i '/name="monday_short"/d' $file
     sed -i '/name="monday_shortest"/d' $file
     sed -i '/name="month_april"/d' $file
     sed -i '/name="month_april_short"/d' $file
     sed -i '/name="month_april_shortest"/d' $file
     sed -i '/name="month_august"/d' $file
     sed -i '/name="month_august_short"/d' $file
     sed -i '/name="month_august_shortest"/d' $file
     sed -i '/name="month_december"/d' $file
     sed -i '/name="month_december_short"/d' $file
     sed -i '/name="month_december_shortest"/d' $file
     sed -i '/name="month_february"/d' $file
     sed -i '/name="month_february_short"/d' $file
     sed -i '/name="month_february_shortest"/d' $file
     sed -i '/name="month_january"/d' $file
     sed -i '/name="month_january_short"/d' $file
     sed -i '/name="month_january_shortest"/d' $file
     sed -i '/name="month_july"/d' $file
     sed -i '/name="month_july_short"/d' $file
     sed -i '/name="month_july_shortest"/d' $file
     sed -i '/name="month_june"/d' $file
     sed -i '/name="month_june_short"/d' $file
     sed -i '/name="month_june_shortest"/d' $file
     sed -i '/name="month_march"/d' $file
     sed -i '/name="month_march_short"/d' $file
     sed -i '/name="month_march_shortest"/d' $file
     sed -i '/name="month_may"/d' $file
     sed -i '/name="month_may_short"/d' $file
     sed -i '/name="month_may_shortest"/d' $file
     sed -i '/name="month_november"/d' $file
     sed -i '/name="month_november_short"/d' $file
     sed -i '/name="month_november_shortest"/d' $file
     sed -i '/name="month_october"/d' $file
     sed -i '/name="month_october_short"/d' $file
     sed -i '/name="month_october_shortest"/d' $file
     sed -i '/name="month_september"/d' $file
     sed -i '/name="month_september_short"/d' $file
     sed -i '/name="month_september_shortest"/d' $file
     sed -i '/name="more"/d' $file
     sed -i '/name="morning"/d' $file
     sed -i '/name="night"/d' $file
     sed -i '/name="noon"/d' $file
     sed -i '/name="pm"/d' $file
     sed -i '/name="saturday"/d' $file
     sed -i '/name="saturday_short"/d' $file
     sed -i '/name="saturday_shortest"/d' $file
     sed -i '/name="search_menu_title"/d' $file
     sed -i '/name="send"/d' $file
     sed -i '/name="solar_term_autumn_begins"/d' $file
     sed -i '/name="solar_term_autumn_equinox"/d' $file
     sed -i '/name="solar_term_clear_and_bright"/d' $file
     sed -i '/name="solar_term_cold_dews"/d' $file
     sed -i '/name="solar_term_grain_buds"/d' $file
     sed -i '/name="solar_term_grain_in_ear"/d' $file
     sed -i '/name="solar_term_grain_rain"/d' $file
     sed -i '/name="solar_term_great_cold"/d' $file
     sed -i '/name="solar_term_great_heat"/d' $file
     sed -i '/name="solar_term_heavy_snow"/d' $file
     sed -i '/name="solar_term_hoar_frost_falls"/d' $file
     sed -i '/name="solar_term_insects_awaken"/d' $file
     sed -i '/name="solar_term_light_snow"/d' $file
     sed -i '/name="solar_term_slight_cold"/d' $file
     sed -i '/name="solar_term_slight_heat"/d' $file
     sed -i '/name="solar_term_spring_begins"/d' $file
     sed -i '/name="solar_term_stopping_the_heat"/d' $file
     sed -i '/name="solar_term_summer_begins"/d' $file
     sed -i '/name="solar_term_summer_solstice"/d' $file
     sed -i '/name="solar_term_the_rains"/d' $file
     sed -i '/name="solar_term_vernal_equinox"/d' $file
     sed -i '/name="solar_term_white_dews"/d' $file
     sed -i '/name="solar_term_winter_begins"/d' $file
     sed -i '/name="solar_term_winter_solstice"/d' $file
     sed -i '/name="status_bar_notification_info_overflow"/d' $file
     sed -i '/name="sunday"/d' $file
     sed -i '/name="sunday_short"/d' $file
     sed -i '/name="sunday_shortest"/d' $file
     sed -i '/name="the_anniversary_of_lifting_martial_law"/d' $file
     sed -i '/name="the_anti_aggression_day"/d' $file
     sed -i '/name="the_arbor_day"/d' $file
     sed -i '/name="the_armed_forces_day"/d' $file
     sed -i '/name="the_armys_day"/d' $file
     sed -i '/name="the_childrens_day"/d' $file
     sed -i '/name="the_chinese_youth_day"/d' $file
     sed -i '/name="the_christmas_day"/d' $file
     sed -i '/name="the_double_ninth_festival"/d' $file
     sed -i '/name="the_dragon_boat_festival"/d' $file
     sed -i '/name="the_easter_day"/d' $file
     sed -i '/name="the_eve_of_the_spring_festival"/d' $file
     sed -i '/name="the_fifth_day"/d' $file
     sed -i '/name="the_fools_day"/d' $file
     sed -i '/name="the_forth_day"/d' $file
     sed -i '/name="the_hksar_establishment_day"/d' $file
     sed -i '/name="the_international_womens_day"/d' $file
     sed -i '/name="the_laba_festival"/d' $file
     sed -i '/name="the_labour_day"/d' $file
     sed -i '/name="the_lantern_festival"/d' $file
     sed -i '/name="the_mid_autumn_festival"/d' $file
     sed -i '/name="the_national_day"/d' $file
     sed -i '/name="the_national_father_day"/d' $file
     sed -i '/name="the_new_years_day"/d' $file
     sed -i '/name="the_night_of_sevens"/d' $file
     sed -i '/name="the_partys_day"/d' $file
     sed -i '/name="the_peace_day"/d' $file
     sed -i '/name="the_retrocession_day"/d' $file
     sed -i '/name="the_second_day"/d' $file
     sed -i '/name="the_seventh_day"/d' $file
     sed -i '/name="the_sixth_day"/d' $file
     sed -i '/name="the_spirit_festival"/d' $file
     sed -i '/name="the_spring_festival"/d' $file
     sed -i '/name="the_teachers_day"/d' $file
     sed -i '/name="the_third_day"/d' $file
     sed -i '/name="the_tw_childrens_day"/d' $file
     sed -i '/name="the_tw_youth_day"/d' $file
     sed -i '/name="the_united_nations_day"/d' $file
     sed -i '/name="the_valentines_day"/d' $file
     sed -i '/name="the_water_lantern_festival"/d' $file
     sed -i '/name="thursday"/d' $file
     sed -i '/name="thursday_short"/d' $file
     sed -i '/name="thursday_shortest"/d' $file
     sed -i '/name="time_picker_dialog_title"/d' $file
     sed -i '/name="time_picker_label_hour"/d' $file
     sed -i '/name="time_picker_label_minute"/d' $file
     sed -i '/name="today"/d' $file
     sed -i '/name="tomorrow"/d' $file
     sed -i '/name="tuesday"/d' $file
     sed -i '/name="tuesday_short"/d' $file
     sed -i '/name="tuesday_shortest"/d' $file
     sed -i '/name="wednesday"/d' $file
     sed -i '/name="wednesday_short"/d' $file
     sed -i '/name="wednesday_shortest"/d' $file
     sed -i '/name="yesterday"/d' $file
     sed -i '/name="v7_preference_off"/d' $file
     sed -i '/name="v7_preference_on"/d' $file    
     sed -i '/wechat/d' $file 
     sed -i '/Wechat/d' $file     
     sed -i '/weibo/d' $file          
     sed -i '/sqlcipher/d' $file       
     sed -i '/China Unicom/d' $file                        
     sed -i '/China Mobile/d' $file                                    
     sed -i '/qq/d' $file 
     sed -i '/_pad/d' $file 
     sed -i '/summary_collapsed_preference_list/d' $file      
     sed -i '/backup_progress_percent_unit/d' $file      
     sed -i '/btn_restore_cancel_app_app/d' $file                
     sed -i '/cloud_backup_detail_app_data/d' $file      
     sed -i '/confirm_restore_app_data_summary/d' $file      
     sed -i '/dialog_app_usage_consent_message/d' $file      
     sed -i '/dump_app_data_record_complete_title/d' $file      
     sed -i '/dump_app_data_record_not_found_msg/d' $file                          
     sed -i '/dump_app_data_record_not_found_title/d' $file                          
     sed -i '/dump_app_data_record_running_msg/d' $file                          
     sed -i '/dump_app_data_record_running_title/d' $file                          
     sed -i '/error_num_placeholder/d' $file          
     sed -i '/pattern_backup_name_with_home/d' $file                                              
     sed -i '/pattern_backup_name_without_home/d' $file                                                                                            
     sed -i '/provision_restore_item_backup_name_with_size/d' $file        
     sed -i '/restore_app_order_search_input_high_light/d' $file                                              
     sed -i '/restore_detail_category_app_data/d' $file                                              
     sed -i '/restoring_app_data_title_no_progress/d' $file                                              
     sed -i '/storage_unit_gb/d' $file                                                                                                        
     sed -i '/storage_unit_mb/d' $file                                                                                                        
     sed -i '/summary_collapsed_preference_list/d' $file       
     sed -i '/share_sdk/d' $file
     sed -i '/talkback_/d' $file     
     sed -i '/mtrl_/d' $file       
     sed -i '/path_/d' $file        
     sed -i '/>com./d' $file    
     sed -i '/_url/d' $file     
     sed -i '/url_/d' $file       
     sed -i '/"ad_/d' $file            
     sed -i '/fold/d' $file   
     sed -i '/xiaoai/d' $file      
     sed -i '/kuyin/d' $file   
     sed -i '/"resource_/d' $file                                                                                
     sed -i '/"abc_/d' $file                                                
     sed -i '/hpplay/d' $file              
     sed -i '/debug/d' $file         
     sed -i '/alipay/d' $file    
     sed -i '/common_google/d' $file               
     sed -i '/express/d' $file      
     sed -i '/flybird/d' $file                                                                  
     sed -i '/mini_/d' $file                                                                  
     sed -i '/msp_/d' $file                                                                  
     sed -i '/didi_/d' $file                                                                  
     sed -i '/airstar_/d' $file                                                                  
     sed -i '/baidu/d' $file                                                                                                             
     sed -i '/mimoji/d' $file                   
     sed -i '/pad_/d' $file      
     sed -i '/"ew_/d' $file                                  
     sed -i '/exo_/d' $file                                  
     sed -i '/_key_/d' $file                                                                             
     sed -i '/pref_/d' $file      
     sed -i '/warningcenter/d' $file                                                                                       
     sed -i '/front_/d' $file     
     sed -i '/back_/d' $file                                                  
     sed -i '/accessibility_/d' $file       
     sed -i '/cityname/d' $file                                                                                                    
     sed -i '/vlog/d' $file                                                                                                         
     sed -i '/xiaomi_/d' $file                                                                                                              
     sed -i '/redmi_/d' $file
     sed -i '/"mi_/d' $file
     sed -i '/_path/d' $file     
     sed -i '/scope_/d' $file          
     sed -i '/material_/d' $file          
     sed -i '/search_/d' $file          
     sed -i '/quick_settings_tiles/d' $file            
     sed -i '/config_/d' $file      
                                          
done     
